; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

@val = addrspace(4) global i256 42
@val2 = addrspace(4) global i256 78

define void @selrrs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selrrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r3
; CHECK-NEXT:    add.eq r2, r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %tmp = select i1 %c, i256 %a, i256 %b
  store i256 %tmp, i256* %data
  ret void
}

define void @selris(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selris:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r2
; CHECK-NEXT:    add.eq 123, r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %tmp = select i1 %c, i256 %a, i256 123
  store i256 %tmp, i256* %data
  ret void
}

define void @selrcs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selrcs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r2
; CHECK-NEXT:    add.eq @val[0], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 %a, i256 %const
  store i256 %tmp, i256* %data
  ret void
}

define void @selrss(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selrss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r2
; CHECK-NEXT:    add.eq stack-[1], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %val2 = load i256, i256 *%data2
  %tmp = select i1 %c, i256 %a, i256 %val2
  store i256 %tmp, i256* %data1
  ret void
}

define void @selirs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selirs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add.ne 123, r0, r2
; CHECK-NEXT:    add r2, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %tmp = select i1 %c, i256 123, i256 %b
  store i256 %tmp, i256* %data
  ret void
}

define void @seliis(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: seliis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add 456, r0, r1
; CHECK-NEXT:    add.ne 123, r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %tmp = select i1 %c, i256 123, i256 456
  store i256 %tmp, i256* %data
  ret void
}

define void @selics(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selics:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add @val[0], r0, r1
; CHECK-NEXT:    add.ne 123, r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 123, i256 %const
  store i256 %tmp, i256* %data
  ret void
}

define void @seliss(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: seliss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add stack-[1], r0, r1
; CHECK-NEXT:    add.ne 123, r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %val2 = load i256, i256 *%data2
  %tmp = select i1 %c, i256 123, i256 %val2
  store i256 %tmp, i256* %data1
  ret void
}

define void @selcrs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selcrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r2
; CHECK-NEXT:    add.ne @val[0], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 %const, i256 %a
  store i256 %tmp, i256* %data
  ret void
}

define void @selcis(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selcis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add 123, r0, r1
; CHECK-NEXT:    add.ne @val[0], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 %const, i256 123
  store i256 %tmp, i256* %data
  ret void
}

define void @selccs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selccs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[1 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add @val2[0], r0, r1
; CHECK-NEXT:    add.ne @val[0], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[1]
; CHECK-NEXT:    ret
  %data = alloca i256
  %const = load i256, i256 addrspace(4)* @val
  %const2 = load i256, i256 addrspace(4)* @val2
  %tmp = select i1 %c, i256 %const, i256 %const2
  store i256 %tmp, i256* %data
  ret void
}

define void @selcss(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selcss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add stack-[1], r0, r1
; CHECK-NEXT:    add.ne @val[0], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %sval2 = load i256, i256 *%data2
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 %const, i256 %sval2
  store i256 %tmp, i256* %data1
  ret void
}

define void @selsrs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selsrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r2
; CHECK-NEXT:    add.ne stack-[1], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %sval2 = load i256, i256 *%data2
  %tmp = select i1 %c, i256 %sval2, i256 %a
  store i256 %tmp, i256* %data1
  ret void
}

define void @selsis(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selsis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add 123, r0, r1
; CHECK-NEXT:    add.ne stack-[1], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %sval2 = load i256, i256 *%data2
  %tmp = select i1 %c, i256 %sval2, i256 123
  store i256 %tmp, i256* %data1
  ret void
}

define void @selscs(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selscs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[2 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add @val[0], r0, r1
; CHECK-NEXT:    add.ne stack-[1], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[2]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %sval2 = load i256, i256 *%data2
  %const = load i256, i256 addrspace(4)* @val
  %tmp = select i1 %c, i256 %sval2, i256 %const
  store i256 %tmp, i256* %data1
  ret void
}

define void @selsss(i256 %a, i256 %b, i1 %c) {
; CHECK-LABEL: selsss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop stack+=[3 + r0]
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add stack-[1], r0, r1
; CHECK-NEXT:    add.ne stack-[2], r0, r1
; CHECK-NEXT:    add r1, r0, stack-[3]
; CHECK-NEXT:    ret
  %data1 = alloca i256
  %data2 = alloca i256
  %data3 = alloca i256
  %sval2 = load i256, i256 *%data2
  %sval3 = load i256, i256 *%data3
  %tmp = select i1 %c, i256 %sval2, i256 %sval3
  store i256 %tmp, i256* %data1
  ret void
}
